return {}

-- return {
--   {
--     "yetone/avante.nvim",
--     event = "VeryLazy",
--     version = false,
--
--     -- KEYBINDINGS
--     keys = {
--       {
--         "<leader>aa",
--         "<cmd>AvanteChat<cr>",
--         desc = "Avante: Open Chat",
--         mode = "n",
--       },
--       {
--         "<leader>ae",
--         "<cmd>AvanteAsk<cr>",
--         desc = "Avante: Ask / Explain selection",
--         mode = "v",
--       },
--       {
--         "<leader>ar",
--         "<cmd>AvanteRefresh<cr>",
--         desc = "Avante: Refresh response",
--         mode = "n",
--       },
--     },
--
--     opts = {
--       provider = "ollama",
--       auto_suggestions_provider = nil,
--
--       providers = {
--         ollama = {
--           model = "mistral:latest",
--           num_ctx = 2048,
--           temperature = 0.2,
--         },
--       },
--     },
--
--     build = "make",
--     dependencies = {
--       "zbirenbaum/copilot.lua",
--       "nvim-treesitter/nvim-treesitter",
--       "stevearc/dressing.nvim",
--       "nvim-lua/plenary.nvim",
--       "MunifTanjim/nui.nvim",
--       "hrsh7th/nvim-cmp",
--       "nvim-tree/nvim-web-devicons",
--     },
--   },
-- }
--
