return {}
-- return {
--   "epwalsh/obsidian.nvim",
--   version = "*",
--   lazy = true,
--   ft = "markdown",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--   },
--   opts = {
--     workspaces = {
--       {
--         name = "zazencodes",
--         path = "~/dotfiles/obsidian/obs vault/",
--       },
--     },
--
--     notes_subdir = "ideas",
--     new_notes_location = "notes/ideas",
--
--     disable_frontmatter = true,
--
--     daily_notes = {
--       folder = "daily",
--       date_format = "%Y-%m-%d",
--       alias_format = "%B %d, %Y",
--     },
--
--     templates = {
--       subdir = "templates",
--       date_format = "%Y-%m-%d",
--       time_format = "%H:%M:%S",
--     },
--
--     mappings = {
--       ["gf"] = {
--         action = function()
--           return require("obsidian").util.gf_passthrough()
--         end,
--         opts = { noremap = false, expr = true, buffer = true },
--       },
--       ["<leader>ti"] = {
--         action = function()
--           return require("obsidian").util.toggle_checkbox()
--         end,
--         opts = { buffer = true },
--       },
--     },
--
--     completion = {
--       nvim_cmp = false,
--       min_chars = 2,
--     },
--
--     ui = {
--       checkboxes = {},
--       bullets = {},
--     },
--   },
-- }
